### ISSUE TITLE
Recruit the Technical Board

### ISSUE THREAD

**Issue by thedrow** [celery/ceps#13]
As described in [CEP-1](https://github.com/celery/ceps/blob/master/draft/0001-cep-process.rst) we need to form a Technical Board to review the technical choices for this project.

The goal of the technical board is to review new CEPs and ensure they are technically sound.
No hands on work is required, although it's certainly encouraged.

@celery/technical-board @celery/core @celery/umbrella @celery/django-celery @celery/kombu 

Below are mentioned current developers with commit rights and the most frequent contributors to each of our repositories.

Please check your username if you have permission to do so or comment if you'd like to be part of the technical board:

### Accepted
- [x] @thedrow
- [x] @georgepsarakis 
- [x] @auvipy
- [x] @frankwiles
- [x] @othalla
- [x] @berkerpeksag
- [x] @alukach
- [x] @jezdez
- [x] @clokep
- [x] @PMickael

### Pending
- [ ] @halfdan
- [ ] @ionelmc
- [ ] @jdufresne
- [ ] @matusvalo
- [ ] @mher 
- [ ] ~@steeve~ 
- [x] @xirdneh
- [ ] @bmbouter
- [ ] @flaper87
- [ ] @AlexHill
- [ ] @andrewsnowden
- [ ] @daevaorn
- [ ] @fireantology
- [ ] @lorenabrams
- [ ] @pelme
- [ ] @rumineykova 
- [ ] @piotrmaslanka
- [ ] @nvie
- [ ] @lorenabrams
- [ ] @heyman
- [ ] @jkozera 
- [ ] @acdha
- [ ] @DXist
- [ ] @toofishes
- [ ] @brianmay
- [ ] @gcachet
- [ ] @streeter
- [ ] @dcramer
- [ ] @Anarchist666
- [ ] @fredj
- [ ] @gthb
- [ ] @brosner
- [ ] @atombrella
- [ ] @nazavode 
- [ ] @dctrwatson
- [ ] @mahendra
- [ ] @beav
- [ ] @reclaro

If you were pinged by accident, I apologize and you may ignore it :)

If you are not on the list and would like to volunteer, please comment here to nominate yourself.
You may also nominate others if they wish to participate.
The existing members will vote to elect new members.

If you'd like to be removed from this list, comment here as well and we will remove you.

If you ignore this issue, in 90 days you will be removed from the list.
You may re-submit yourself at a later time.

**Comment by othalla** [comment]
I'll be glad to help and participate if i can!

**Comment by berkerpeksag** [comment]
You can count me in! However, please note that I just moved to a new country and I might be unavailable until this summer.

Also, I'm a [PEP editor](https://www.python.org/dev/peps/pep-0001/#pep-editors) and I can help with the whole CEP process, if needed.

**Comment by luisehk** [comment]
I'd love to participate. Just read CEP-1 and I can help in the whole process too.

**Comment by auvipy** [comment]
I would love to participate.

**Comment by auvipy** [comment]
@berkerpeksag It would be really great to have some input from the interested Python core team members to leave their inputs and at least if possible, review or help us in fixing some long-standing issues and some future direction in the technical area of celery next.

**Comment by alukach** [comment]
Great work, I think CEP-1 is excellently written and something like this will definitely benefit the Celery project (both for the sake of internal direction and for external understanding of the project).  Is this format used elsewhere?  This seems like a great start for generalized open source governance that could be applied to any project, this kind of structure would be useful in a guide for "how to run an OSS project".

Anyways, regarding my involvement, I'm happy to be involved but am unable to make any firm commitments regarding the amount of hours I can dedicate to something like this.  I admit that I haven't been using Celery much (or Python, for that matter) as of late, so if your efforts are to keep the board small and extremely focused I would say that you would do better to go without me; however if it's a "the more, the merrier" type of situation, count me in.

**Comment by auvipy** [comment]
@alukach you are always welcome to share your previous experience for designing celery next major version. We don't have any firm choice for that if you feel you could contribute by sharing your previous knowledge it is greatly welcome. if you believe anything you could help in the process :) as you contributed to celery previously or worked with it as far I can recall.

**Comment by milindparvatia** [comment]
I'm not on the list but I would like to participate and provide support to the team.

**Comment by georgepsarakis** [comment]
@thedrow you can include me as well!

**Comment by thedrow** [comment]
@alukach We will create technical working groups so that each and every member with the exception of the core development team can focus on one topic.

CEP-1 is copied almost directly from Django's DEP-1.

**Comment by thedrow** [comment]
@milindparvatia Pick an issue from this repository, I'll shepherd.
If you can complete one CEP, we'll vote on your nomination.

**Comment by frankwiles** [comment]
I'd be happy to participate if ya'll think I would be useful!

**Comment by auvipy** [comment]
participation are always welcome!! thanks for your interest!! @frankwiles

**Comment by thedrow** [comment]
No other takers?

**Comment by jezdez** [comment]
> No other takers?

Whoops, I missed this, I'm happy to help!

**Comment by clokep** [comment]
@thedrow I'd be tentatively interested, although it isn't entirely clear to me what qualifications or expectations there are for members of this board.

**Comment by thedrow** [comment]
@clokep Review CEPS and ensure they are technically sound.
Right now we're working on our Celery 5 effort through CEPS.
See #19 for details.

**Comment by thedrow** [comment]
The deadline for applications is today.
We will reiterate this process yearly or as needed.

**Comment by PMickael** [comment]
Hello, i'm in too ! 👍

**Comment by smarzola** [comment]
Hi, my company is using Celery extensively and we're happy to be part of Technical Board.
@gasbasd @simobasso @SharpEdgeMarshall

**Comment by simobasso** [comment]
Yes! Happy to help!

**Comment by SharpEdgeMarshall** [comment]
Sure, we are using Celery in production and really interested in its evolution.

**Comment by mahendra** [comment]
At Affirm, we use celery heavily in production. So, I would like to be a part of this. I would also like to nominate @srikiraju to be a member.

**Comment by thedrow** [comment]
I've invited you all.

**Comment by devilicecream** [comment]
Hi guys, I've been working with Celery for a while and I'd be really happy to join the board and contribute :)

**Comment by matteius** [comment]
I've been spending time on the Issues and we have been using Celery in production for 7 years now.  Let me know how you'd like additional help, and I'll keep trying to crush understanding the existing code.

**Comment by auvipy** [comment]
you are welcome

**Comment by xirdneh** [comment]
How can I go from Pending to Accepted?
Thanks.

**Comment by auvipy** [comment]
you are accepted

**Comment by steeve** [comment]
hey folks, as much as I am flattered of being here, you might want to remove me as I haven't been active on celery for at least 5-6 years :)

**Comment by jheld** [comment]
I haven't had many contributions to celery yet but I/my company rely heavily on celery (and flower, with maintenance/contribution there). I did post on the core dev issue as well. Would be very interested to be involved in conversations/design, assuming the list isn't super saturated yet.

**Comment by auvipy** [comment]
> I haven't had many contributions to celery yet but I/my company rely heavily on celery (and flower, with maintenance/contribution there, too). I did post on the core dev issue as well. Would be very interested to be involved in conversations/design, assuming the list isn't super saturated yet.

you are welcome on technical board. But for being considered to be in the core team, need good upstream contributions.

**Comment by thedrow** [comment]
I invited all those who requested access.
I'm going to close this issue and no further submissions will be accepted for now.
We will revisit next year or review requests on a particular basis if required.

**Comment by jheld** [comment]
I did request a couple days ago. But yes, if not this year, happy to be considered later.
