### ISSUE TITLE
Formalize the Core Developers team

### ISSUE THREAD

**Issue by thedrow** [celery/ceps#14]
As described in [CEP-1](https://github.com/celery/ceps/blob/master/draft/0001-cep-process.rst) we need to form a Core Developers team which will have commit access to all repositories of the project.
I think that in order to ensure the longevity of the project and as a way to express our gratitude, @ask should remain a core developer for life. 

Please check your username if you have permission to do so or comment if you'd like to be part of the core developers team:
- [x] @ask 
- [x] @thedrow
- [x] @auvipy 
- [x] @georgepsarakis
- [ ] ~@ionelmc~ 
- [ ] @matusvalo
- [x] @mher 
- [ ] ~@steeve~
- [x] @xirdneh

If you were pinged by accident, I apologize and you may ignore it :)

If you are not on the list and would like to volunteer, please comment here to nominate yourself.
You may also nominate others if they wish to participate.
The existing members will vote to elect new members.

If you'd like to be removed from this list, comment here as well and we will remove you.

If you ignore this issue, in 90 days you will be removed from the list.
You may re-submit yourself at a later time.

**Comment by luisehk** [comment]
I'd love to participate.

**Comment by georgepsarakis** [comment]
@thedrow I read the very detailed [CEP-1](https://github.com/celery/ceps/blob/master/draft/0001-cep-process.rst), but not sure I understand entirely. May I ask what are the differences between the Technical Board and Core Developers?

**Comment by thedrow** [comment]
The Technical Board drives decisions.
The Core Developers team reviews contributions and merges them, enforces the Technical Board's decisions and contributes code, documentation and new CEPs.

**Comment by georgepsarakis** [comment]
Thanks for the feedback! Perhaps you would like to include me in the list as well?

**Comment by auvipy** [comment]
I believe we should add George :D

**Comment by simobasso** [comment]
Hi! I'm happy to help also on issues and PRs

**Comment by SharpEdgeMarshall** [comment]
Me too, I'm already trying to be more active on PRs!

**Comment by gasbasd** [comment]
hi, i'm @simobasso and @SharpEdgeMarshall colleague and i would love to join the core team

**Comment by devilicecream** [comment]
Hi guys! I'd like to join too, I work with @simobasso @gasbasd and @SharpEdgeMarshall and been working with Celery for a while. Would be happy to contribute!

**Comment by auvipy** [comment]
those who don't have celery contribution, get more engaged. otherwise you won/t be able to join core team. contributions are the key here.

**Comment by simobasso** [comment]
LGTM :+1:

**Comment by xirdneh** [comment]
Commenting here to record my interest on continuing participation in the project.

**Comment by jheld** [comment]
Also commenting to show interest. Between here & flower (realizing that project is not directly in the umbrella), I and my company use these technologies a ton. Happy to contribute here more!

**Comment by steeve** [comment]
Hey guys, I haven't been active in the last 8 years on Celery. I'm flattered though :D

**Comment by thedrow** [comment]
@ionelmc and @matusvalo did not respond.
Please let us know if you'd like to remain or be removed.

**Comment by matteius** [comment]
I am definitely interesting in increasing my efforts to becoming a core celery developer -- I think if you look at the last year I have already increased my number of contribution and willing to step it up beyond that.

**Comment by auvipy** [comment]
> I am definitely interesting in increasing my efforts to becoming a core celery developer -- I think if you look at the last year I have already increased my number of contribution and willing to step it up beyond that.

keep contributing on a regular basis. the quality & quantity of your contribution will help us decide about you.

**Comment by matteius** [comment]
@auvipy  Thanks for your help so far.

**Comment by ionelmc** [comment]
Hello, sorry for the tardiness. I'm interested but I don't have time to do anything in the foreseeable future. If I get to work on a big celery-using project I will, but that's hard to predict.

**Comment by thedrow** [comment]
We will remove you for now.
Please nominate yourself in the future if you'd like to participate.

**Comment by thedrow** [comment]
We're way past the deadline.

To everyone who volunteered to participate, I'd like to see more involvement before we add you officially.
